settings = {
    'track_length': 5784.02,
    'log_keys': [
        'angle',
        'curLapTime',
        'damage',
        'distFromStart',
        'distRaced',
        'fuel',
        'gear',
        'lastLapTime',
        'opponents',
        'racePos',
        'rpm',
        'speedX',
        'speedY',
        'speedZ',
        'track',
        'trackPos',
        'wheelSpinVel',
        'z',
        'focus',
        'x',
        'y',
        'roll',
        'pitch',
        'yaw',
        'speedGlobalX',
        'speedGlobalY',
        'clutch',
        'accel',
        'brake',
        'steer',
        'meta'
    ]
}
